// src/app/components/scroll/scroll.component.ts
import { Component, OnInit } from '@angular/core';
import { ViewBoxService } from 'src/app/services/view-box.service';

@Component({
  selector: 'app-scroll',
  templateUrl: './scroll.component.html',
  styleUrls: ['./scroll.component.sass']
})
export class ScrollComponent implements OnInit {

  readonly HORIZONTAL = true;
  readonly VERTICAL = false;
  readonly LEFT_OR_UP = true;
  readonly RIGHT_OR_DOWN = false;
  private timerScroll: number;


  constructor(private viewBoxService: ViewBoxService) { }

  ngOnInit(): void {
  }

  scroll(isHorizontal: boolean, isTopOrLeft: boolean, value: number = 10) {
    this.viewBoxService.change(null, {orientation:isHorizontal,direction:isTopOrLeft,value:value});
  }

	moveScrollPressed(isHorizontal: boolean, isTopOrLeft: boolean) {
		let velocidad: number = 500;
		this.timerScroll = <any>setInterval(() => {
			this.scroll(isHorizontal, isTopOrLeft);
		}, velocidad);
	}


	stopScroll() {
		if (this.timerScroll) {
			clearInterval(this.timerScroll);
		}
	}

}


<app-circle-button
isFloat="true"
position="top"
icon="keyboard_arrow_up"
(click)="scroll(VERTICAL, LEFT_OR_UP)"
(dblclick)="scroll(VERTICAL, LEFT_OR_UP, 80)"
(mousedown)="moveScrollPressed(VERTICAL, LEFT_OR_UP)"
(mouseup)="stopScroll()"
(mouseleave)="stopScroll()">
</app-circle-button>
<app-circle-button
isFloat="true"
position="bottom"
icon="keyboard_arrow_down"
(click)="scroll(VERTICAL, RIGHT_OR_DOWN)"
(dblclick)="scroll(VERTICAL, RIGHT_OR_DOWN, 80)"
(mousedown)="moveScrollPressed(VERTICAL, RIGHT_OR_DOWN)"
(mouseup)="stopScroll()"
(mouseleave)="stopScroll()">
</app-circle-button>
<app-circle-button
isFloat="true"
position="left"
icon="keyboard_arrow_left"
(click)="scroll(HORIZONTAL, LEFT_OR_UP)"
(dblclick)="scroll(HORIZONTAL, LEFT_OR_UP, 80)"
(mousedown)="moveScrollPressed(HORIZONTAL, LEFT_OR_UP)"
(mouseup)="stopScroll()"
(mouseleave)="stopScroll()">
</app-circle-button>
<app-circle-button
isFloat="true"
position="right"
icon="keyboard_arrow_right"
(click)="scroll(HORIZONTAL, RIGHT_OR_DOWN)"
(dblclick)="scroll(HORIZONTAL, RIGHT_OR_DOWN, 80)"
(mousedown)="moveScrollPressed(HORIZONTAL, RIGHT_OR_DOWN)"
(mouseup)="stopScroll()"
(mouseleave)="stopScroll()">
</app-circle-button>

// src/components/Scroll/Scroll.tsx
import React, { useRef } from 'react';
import { useWhiteboard } from '../../context/WhiteboardContext';
import { CircleButton } from '../CircleButton/CircleButton';

export const Scroll: React.FC = () => {
  const { scroll } = useWhiteboard();
  const timerRef = useRef<number | null>(null);

  const HORIZONTAL = true;
  const VERTICAL = false;
  const LEFT_OR_UP = true;
  const RIGHT_OR_DOWN = false;

  const handleScroll = (isHorizontal: boolean, isTopOrLeft: boolean, value = 10) => {
    scroll(isHorizontal, isTopOrLeft, value);
  };

  const handleMouseDown = (isHorizontal: boolean, isTopOrLeft: boolean) => {
    stopScroll();
    timerRef.current = window.setInterval(() => {
      handleScroll(isHorizontal, isTopOrLeft, 10);
    }, 500);
  };

  const stopScroll = () => {
    if (timerRef.current !== null) {
      clearInterval(timerRef.current);
      timerRef.current = null;
    }
  };

  return (
    <>
      <CircleButton
        isFloat={true}
        position="top"
        icon="keyboard_arrow_up"
        onClick={() => handleScroll(VERTICAL, LEFT_OR_UP)}
        onDoubleClick={() => handleScroll(VERTICAL, LEFT_OR_UP, 80)}
        onMouseDown={() => handleMouseDown(VERTICAL, LEFT_OR_UP)}
        onMouseUp={stopScroll}
        onMouseLeave={stopScroll}
      />
      <CircleButton
        isFloat={true}
        position="bottom"
        icon="keyboard_arrow_down"
        onClick={() => handleScroll(VERTICAL, RIGHT_OR_DOWN)}
        onDoubleClick={() => handleScroll(VERTICAL, RIGHT_OR_DOWN, 80)}
        onMouseDown={() => handleMouseDown(VERTICAL, RIGHT_OR_DOWN)}
        onMouseUp={stopScroll}
        onMouseLeave={stopScroll}
      />
      <CircleButton
        isFloat={true}
        position="left"
        icon="keyboard_arrow_left"
        onClick={() => handleScroll(HORIZONTAL, LEFT_OR_UP)}
        onDoubleClick={() => handleScroll(HORIZONTAL, LEFT_OR_UP, 80)}
        onMouseDown={() => handleMouseDown(HORIZONTAL, LEFT_OR_UP)}
        onMouseUp={stopScroll}
        onMouseLeave={stopScroll}
      />
      <CircleButton
        isFloat={true}
        position="right"
        icon="keyboard_arrow_right"
        onClick={() => handleScroll(HORIZONTAL, RIGHT_OR_DOWN)}
        onDoubleClick={() => handleScroll(HORIZONTAL, RIGHT_OR_DOWN, 80)}
        onMouseDown={() => handleMouseDown(HORIZONTAL, RIGHT_OR_DOWN)}
        onMouseUp={stopScroll}
        onMouseLeave={stopScroll}
      />
    </>
  );
};
