// src/App.tsx
import React from 'react';
import { WhiteboardProvider } from './context/WhiteboardContext';
import { Page } from './components/Page/Page';
import { Scroll } from './components/Scroll/Scroll';
import { Property } from './components/Property/Property';
import { Control } from './components/Control/Control';
import './App.scss';

export const App: React.FC = () => {
  return (
    <WhiteboardProvider>
      <Page />
      <Scroll />
      <div className="content" role="main">
        <Property />
        <Control />
      </div>
    </WhiteboardProvider>
  );
};

export default App;

// src/app/app.component.ts
import { Component } from "@angular/core";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.sass"],
})
export class AppComponent {
  title = "board";
}

<app-page></app-page>
<app-scroll></app-scroll>
<div class="content" role="main">
  <app-property></app-property>
  <app-control></app-control>
</div>
<router-outlet></router-outlet>
