// src/components/Control/Control.tsx
import React from 'react';
import { useWhiteboard } from '../../context/WhiteboardContext';
import { CircleButton } from '../CircleButton/CircleButton';
import { TypeShape } from '../../types/shape';
import styles from './Control.module.scss';

export const Control: React.FC = () => {
  const {
    activeTool,
    setActiveTool,
    canUndo,
    canRedo,
    undo,
    redo,
    changeZoom,
  } = useWhiteboard();

  return (
    <div className={styles.container}>
      <CircleButton
        icon="undo"
        info="Deshacer (⌘Z / Ctrl+Z)"
        disabled={!canUndo}
        onClick={undo}
      />
      <CircleButton
        icon="redo"
        info="Rehacer (⌘⇧Z / Ctrl+Y)"
        disabled={!canRedo}
        onClick={redo}
      />
      <span className={styles.space}></span>
      <CircleButton
        icon="pan_tool"
        info="Seleccionar (V / Esc)"
        isSelected={activeTool === null}
        onClick={() => setActiveTool(null)}
      />
      <CircleButton
        icon="title"
        info="Texto (T)"
        isSelected={activeTool === TypeShape.TEXT}
        onClick={() => setActiveTool(TypeShape.TEXT)}
      />
      <CircleButton
        icon="remove"
        rotateIcon="rotate(45deg)"
        info="Línea (L)"
        isSelected={activeTool === TypeShape.LINE}
        onClick={() => setActiveTool(TypeShape.LINE)}
      />
      <CircleButton
        icon="show_chart"
        info="Polilínea (P)"
        isSelected={activeTool === TypeShape.POLYLINE}
        onClick={() => setActiveTool(TypeShape.POLYLINE)}
      />
      <CircleButton
        icon="check_box_outline_blank"
        info="Rectángulo (R)"
        isSelected={activeTool === TypeShape.RECT}
        onClick={() => setActiveTool(TypeShape.RECT)}
      />
      <CircleButton
        icon="radio_button_unchecked"
        info="Elipse (E)"
        isSelected={activeTool === TypeShape.ELLIPSE}
        onClick={() => setActiveTool(TypeShape.ELLIPSE)}
      />
      <span className={styles.space}></span>
      <CircleButton
        icon="zoom_in"
        info="Ampliar (Ctrl + Scroll ↑)"
        onClick={() => changeZoom(true)}
      />
      <CircleButton
        icon="zoom_out"
        info="Disminuir (Ctrl + Scroll ↓)"
        onClick={() => changeZoom(false)}
      />
      <CircleButton
        icon="fullscreen_exit"
        info="Reestablecer Zoom (100%)"
        onClick={() => changeZoom(100)}
      />
    </div>
  );
};

// src/app/components/control/control.component.ts
import { Component, OnInit } from "@angular/core";

@Component({
  selector: "app-control",
  templateUrl: "./control.component.html",
  styleUrls: ["./control.component.sass"],
})
export class ControlComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {}
}

<div class="container">
  <app-circle-button
    icon="undo"
    info="Deshacer"
    *ngIf="viewBoxService.historialViews.length > 0"
    (click)="viewBoxService.undoView()"
  ></app-circle-button>
  <app-circle-button
    icon="redo"
    info="Rehacer"
    *ngIf="viewBoxService.deleteViews.length > 0"
    (click)="viewBoxService.redoView()"
  ></app-circle-button>
  <span class="space"></span>
  <app-circle-button
    icon="pan_tool"
    info="Seleccionar"
    [isSelected]="shapeEventService.typeShape == null"
    (click)="selectShape()"
  ></app-circle-button>
  <app-circle-button
    icon="title"
    info="Texto"
    [isSelected]="shapeEventService.typeShape == 'foreignObject'"
    (click)="selectText()"
  ></app-circle-button>
  <app-circle-button
    icon="remove"
    rotateIcon="rotate(45deg)"
    info="Línea"
    [isSelected]="shapeEventService.typeShape == 'line'"
    (click)="selectLine()"
  ></app-circle-button>
  <app-circle-button
    icon="show_chart"
    info="Polilínea"
    [isSelected]="shapeEventService.typeShape == 'polyline'"
    (click)="selectPolyline()"
  ></app-circle-button>
  <app-circle-button
    icon="check_box_outline_blank"
    info="Rectángulo"
    [isSelected]="shapeEventService.typeShape == 'rect'"
    (click)="selectRect()"
  ></app-circle-button>
  <app-circle-button
    icon="radio_button_unchecked"
    info="Elipse"
    [isSelected]="shapeEventService.typeShape == 'ellipse'"
    (click)="selectEllipse()"
  ></app-circle-button>
  <span class="space"></span>
  <app-circle-button
    icon="zoom_in"
    info="Ampliar"
    (click)="zoom(ZOOM_IN)"
  ></app-circle-button>
  <app-circle-button
    icon="zoom_out"
    info="Disminuir"
    (click)="zoom(ZOOM_OUT)"
  ></app-circle-button>
  <app-circle-button
    icon="fullscreen_exit"
    info="Reestablecer"
    (click)="zoom(ZOOM_100)"
  ></app-circle-button>
</div>
